# Generated by Django 6.0.5 on 2026-07-08 14:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_product_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2026, 7, 8, 14, 53, 32, 280427, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AddField(
            model_name='product',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2026, 7, 8, 14, 53, 32, 280427, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AddField(
            model_name='review',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2026, 7, 8, 14, 53, 32, 280427, tzinfo=datetime.timezone.utc)),
        ),
    ]
