# Generated by Django 6.0.5 on 2026-07-14 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_product_average_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='status',
            field=models.CharField(default='Нет оценок', max_length=30),
        ),
    ]
